// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwRR5oYy6kwozMDf84FvHZYTVotJHtL0s',
    appId: '1:830997393282:android:ee1ab19acc4ba155d1699b',
    messagingSenderId: '830997393282',
    projectId: 'skillzy-55f5e',
    storageBucket: 'skillzy-55f5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNs0ImR_Ogfu_s00V2j6nH-gfd4-im1zY',
    appId: '1:830997393282:ios:93239474c9ad6652d1699b',
    messagingSenderId: '830997393282',
    projectId: 'skillzy-55f5e',
    storageBucket: 'skillzy-55f5e.firebasestorage.app',
    androidClientId: '830997393282-ga4h5t02tl3h4eji97f1ebsolbkn49p0.apps.googleusercontent.com',
    iosClientId: '830997393282-mq1844q3r7j4l2l03vib8cq6741rah7q.apps.googleusercontent.com',
    iosBundleId: 'com.skillzy.app.skillzy',
  );
}
